// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracker.proto

// Protobuf Java Version: 3.25.3
package com.ansoncht.catfoodtracker.proto;

public interface CreateCatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tracker.CreateCatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the cat.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the cat.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The age of the cat in years.
   * </pre>
   *
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <pre>
   * The breed of the cat.
   * </pre>
   *
   * <code>string breed = 3;</code>
   * @return The breed.
   */
  java.lang.String getBreed();
  /**
   * <pre>
   * The breed of the cat.
   * </pre>
   *
   * <code>string breed = 3;</code>
   * @return The bytes for breed.
   */
  com.google.protobuf.ByteString
      getBreedBytes();
}
