// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracker.proto

// Protobuf Java Version: 3.25.3
package com.ansoncht.catfoodtracker.proto;

/**
 * <pre>
 * CreateCatReply represents the output structure for the CreateCat RPC.
 * It provides feedback about the cat creation process, indicating
 * whether the creation was successful and include additional
 * information such as a cat id.
 * </pre>
 *
 * Protobuf type {@code tracker.CreateCatReply}
 */
public final class CreateCatReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tracker.CreateCatReply)
    CreateCatReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateCatReply.newBuilder() to construct.
  private CreateCatReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateCatReply() {
    catId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateCatReply();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ansoncht.catfoodtracker.proto.TrakerProto.internal_static_tracker_CreateCatReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ansoncht.catfoodtracker.proto.TrakerProto.internal_static_tracker_CreateCatReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ansoncht.catfoodtracker.proto.CreateCatReply.class, com.ansoncht.catfoodtracker.proto.CreateCatReply.Builder.class);
  }

  public static final int CAT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object catId_ = "";
  /**
   * <pre>
   * The user_id of the Cat
   * </pre>
   *
   * <code>string cat_id = 1;</code>
   * @return The catId.
   */
  @java.lang.Override
  public java.lang.String getCatId() {
    java.lang.Object ref = catId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      catId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The user_id of the Cat
   * </pre>
   *
   * <code>string cat_id = 1;</code>
   * @return The bytes for catId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCatIdBytes() {
    java.lang.Object ref = catId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      catId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(catId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, catId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(catId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, catId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ansoncht.catfoodtracker.proto.CreateCatReply)) {
      return super.equals(obj);
    }
    com.ansoncht.catfoodtracker.proto.CreateCatReply other = (com.ansoncht.catfoodtracker.proto.CreateCatReply) obj;

    if (!getCatId()
        .equals(other.getCatId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CAT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCatId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ansoncht.catfoodtracker.proto.CreateCatReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ansoncht.catfoodtracker.proto.CreateCatReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * CreateCatReply represents the output structure for the CreateCat RPC.
   * It provides feedback about the cat creation process, indicating
   * whether the creation was successful and include additional
   * information such as a cat id.
   * </pre>
   *
   * Protobuf type {@code tracker.CreateCatReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tracker.CreateCatReply)
      com.ansoncht.catfoodtracker.proto.CreateCatReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ansoncht.catfoodtracker.proto.TrakerProto.internal_static_tracker_CreateCatReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ansoncht.catfoodtracker.proto.TrakerProto.internal_static_tracker_CreateCatReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ansoncht.catfoodtracker.proto.CreateCatReply.class, com.ansoncht.catfoodtracker.proto.CreateCatReply.Builder.class);
    }

    // Construct using com.ansoncht.catfoodtracker.proto.CreateCatReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      catId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ansoncht.catfoodtracker.proto.TrakerProto.internal_static_tracker_CreateCatReply_descriptor;
    }

    @java.lang.Override
    public com.ansoncht.catfoodtracker.proto.CreateCatReply getDefaultInstanceForType() {
      return com.ansoncht.catfoodtracker.proto.CreateCatReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.ansoncht.catfoodtracker.proto.CreateCatReply build() {
      com.ansoncht.catfoodtracker.proto.CreateCatReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ansoncht.catfoodtracker.proto.CreateCatReply buildPartial() {
      com.ansoncht.catfoodtracker.proto.CreateCatReply result = new com.ansoncht.catfoodtracker.proto.CreateCatReply(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ansoncht.catfoodtracker.proto.CreateCatReply result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.catId_ = catId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ansoncht.catfoodtracker.proto.CreateCatReply) {
        return mergeFrom((com.ansoncht.catfoodtracker.proto.CreateCatReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ansoncht.catfoodtracker.proto.CreateCatReply other) {
      if (other == com.ansoncht.catfoodtracker.proto.CreateCatReply.getDefaultInstance()) return this;
      if (!other.getCatId().isEmpty()) {
        catId_ = other.catId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              catId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object catId_ = "";
    /**
     * <pre>
     * The user_id of the Cat
     * </pre>
     *
     * <code>string cat_id = 1;</code>
     * @return The catId.
     */
    public java.lang.String getCatId() {
      java.lang.Object ref = catId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        catId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The user_id of the Cat
     * </pre>
     *
     * <code>string cat_id = 1;</code>
     * @return The bytes for catId.
     */
    public com.google.protobuf.ByteString
        getCatIdBytes() {
      java.lang.Object ref = catId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        catId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The user_id of the Cat
     * </pre>
     *
     * <code>string cat_id = 1;</code>
     * @param value The catId to set.
     * @return This builder for chaining.
     */
    public Builder setCatId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      catId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The user_id of the Cat
     * </pre>
     *
     * <code>string cat_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCatId() {
      catId_ = getDefaultInstance().getCatId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The user_id of the Cat
     * </pre>
     *
     * <code>string cat_id = 1;</code>
     * @param value The bytes for catId to set.
     * @return This builder for chaining.
     */
    public Builder setCatIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      catId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tracker.CreateCatReply)
  }

  // @@protoc_insertion_point(class_scope:tracker.CreateCatReply)
  private static final com.ansoncht.catfoodtracker.proto.CreateCatReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ansoncht.catfoodtracker.proto.CreateCatReply();
  }

  public static com.ansoncht.catfoodtracker.proto.CreateCatReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateCatReply>
      PARSER = new com.google.protobuf.AbstractParser<CreateCatReply>() {
    @java.lang.Override
    public CreateCatReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateCatReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateCatReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ansoncht.catfoodtracker.proto.CreateCatReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

