// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracker.proto

// Protobuf Java Version: 3.25.3
package com.ansoncht.catfoodtracker.proto;

public interface CreateCatReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tracker.CreateCatReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The user_id of the Cat
   * </pre>
   *
   * <code>string cat_id = 1;</code>
   * @return The catId.
   */
  java.lang.String getCatId();
  /**
   * <pre>
   * The user_id of the Cat
   * </pre>
   *
   * <code>string cat_id = 1;</code>
   * @return The bytes for catId.
   */
  com.google.protobuf.ByteString
      getCatIdBytes();
}
