// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracker.proto

// Protobuf Java Version: 3.25.3
package com.ansoncht.catfoodtracker.proto;

public interface CreateUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tracker.CreateUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The first name of the user
   * </pre>
   *
   * <code>string first_name = 1;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <pre>
   * The first name of the user
   * </pre>
   *
   * <code>string first_name = 1;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <pre>
   * The last name of the user
   * </pre>
   *
   * <code>string last_name = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <pre>
   * The last name of the user
   * </pre>
   *
   * <code>string last_name = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <pre>
   * The username of the user
   * </pre>
   *
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <pre>
   * The username of the user
   * </pre>
   *
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   * The email of the user
   * </pre>
   *
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <pre>
   * The email of the user
   * </pre>
   *
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   * The password of the user
   * </pre>
   *
   * <code>string password = 5;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <pre>
   * The password of the user
   * </pre>
   *
   * <code>string password = 5;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <pre>
   * The confirmed password of the user
   * </pre>
   *
   * <code>string confirmed_password = 6;</code>
   * @return The confirmedPassword.
   */
  java.lang.String getConfirmedPassword();
  /**
   * <pre>
   * The confirmed password of the user
   * </pre>
   *
   * <code>string confirmed_password = 6;</code>
   * @return The bytes for confirmedPassword.
   */
  com.google.protobuf.ByteString
      getConfirmedPasswordBytes();
}
