// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracker.proto

// Protobuf Java Version: 3.25.3
package com.ansoncht.catfoodtracker.proto;

public interface CreateUserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tracker.CreateUserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The user_id of the User
   * </pre>
   *
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * The user_id of the User
   * </pre>
   *
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * The email of the User
   * </pre>
   *
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <pre>
   * The email of the User
   * </pre>
   *
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   * The username of the User
   * </pre>
   *
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <pre>
   * The username of the User
   * </pre>
   *
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   * The error of the User
   * </pre>
   *
   * <code>string error = 4;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <pre>
   * The error of the User
   * </pre>
   *
   * <code>string error = 4;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
